### ISSUE TITLE
Disappearance of skill level descriptions for some skills

### ISSUE THREAD

**Issue by hjbwynne** [backstagetechnicalservices/website#68]
Descriptions for levels 1, 2 and 3 for "Video Technician - Advanced" and "Lighting Programmer - Eos (basic) as well as level 2 for "Catering - Assistant Chef" have disappeared. Assignments to levels and other skills appear unaffected.

**Comment by bnjns** [comment]
Are you sure they've disappeared? Many skills are just lacking in descriptions and/or level requirements.

**Comment by bnjns** [comment]
There is nothing to imply that this is the case. There is nothing in any of the logs that indicate changes have been made to any training skills, and without further information there's really nothing I can do.

Very little code runs on its own, and none of that code interacts with the training skills, so if this does happen it'll be caused by someone visiting the site (not saying they'd cause it, but their visit would be what triggers a bug). All I can recommend is you keep a close eye and if this happens again you report it immediately and provide as much information as you can regarding what you were doing around the time you noticed (it's really important to make sure I know when it happened, otherwise there's very little chance of tracking down what, if anything, happened).

In all honesty, I don't think anything has happened - IIRC (and I was T&S for 2 years), the skills you mentioned have always been that empty. I hope this response is okay.
